---

libraries_apt:
  - unzip

wso2studio_version    : "3.8.0"

wso2studio:
  referer     : "http://connect.wso2.com/wso2/getform/reg/new_product_download"
  url         : "https://product-dist.wso2.com/products/developer-studio/{{ wso2studio_version }}/"
  zip         : "developer-studio-eclipse-jee-luna-linux-gtk-x86_64-{{ wso2studio_version }}.zip"
  home        : "/usr/lib/wso2studio"

desktop : "wso2studio"

